# command line: main.py --config config/nturgbd120-cross-subject/joint.yaml --model model.Hyperformer.Model --work-dir work_dir/ntu120/csub/Hyperformer_joint --device 2 3 --base-lr 2.5e-2

base_lr: 0.025
batch_size: 64
config: config/nturgbd120-cross-subject/joint.yaml
device:
- 2
- 3
ema: false
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
joint_label: []
lambda_1: 0.0001
lambda_2: 0.1
log_interval: 100
lr_decay_rate: 0.1
model: model.Hyperformer.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  joint_label:
  - 0
  - 4
  - 2
  - 2
  - 2
  - 2
  - 1
  - 1
  - 2
  - 2
  - 1
  - 1
  - 2
  - 3
  - 3
  - 3
  - 2
  - 3
  - 3
  - 3
  - 1
  - 0
  - 1
  - 0
  - 1
  num_class: 120
  num_person: 2
  num_point: 25
model_saved_name: ''
momentum: 0.9
nesterov: true
num_epoch: 140
num_worker: 48
optimizer: SGD
phase: train
print_log: true
save_epoch: 10
save_interval: 1
save_score: false
seed: 2
show_topk:
- 1
- 5
start_epoch: 0
step:
- 110
- 120
test_batch_size: 512
test_feeder_args:
  bone: false
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: work_dir/ntu120/csub/Hyperformer_joint
